version: "3.7"
services: 

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    ports: 
      - "9200:9200"
      - "9300:9300"
    environment: 
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - monitoring

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.6.2
    user: root
    depends_on: 
      - elasticsearch
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment: 
      - strict.perms=false
      - output.elasticsearch.hosts=["elasticsearch:9200"]
    networks:
      - monitoring

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    depends_on: 
      - elasticsearch
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - monitoring

  apm-server:
    image: docker.elastic.co/apm/apm-server:7.6.2
    depends_on: 
      - elasticsearch
    volumes: 
      - ./apm-server.yml:/usr/share/apm-server/apm-server.yml:ro
    environment: 
      - strict.perms=false
      - output.elasticsearch.hosts=["elasticsearch:9200"]
    networks: 
      - monitoring


  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.6.2
    user: root
    depends_on: 
      - elasticsearch
    volumes: 
      - ./metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
    environment: 
      - setup.kibana.host=kibana:5601
      - output.elasticsearch.hosts=["elasticsearch:9200"]
    networks: 
      - monitoring

  prometheus:
    image: prom/prometheus:v2.18.0
    volumes: 
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks: 
      - monitoring

  grafana:
    image: grafana/grafana:6.7.3
    ports: 
      - "3000:3000"
    # environment: 
      # GF_INSTALL_PLUGINS: grafana-clock-panel 1.0.1,grafana-simple-json-datasource 1.3.5
    networks: 
      - monitoring

  echoserver:
    build: ./echoserver
    ports:
      - 8080:8080
    environment: 
      ELASTIC_APM_SERVICE_NAME: echoserver            # default to binary name
      ELASTIC_APM_SERVER_URL: http://apm-server:8200
      ELASTIC_APM_METRICS_INTERVAL: 3s                # default to 30sec
      # ELASTIC_APM_LOG_LEVEL: debug
      # ELASTIC_APM_LOG_FILE: stderr
    networks:
      - monitoring
      - app

  mathserver:
    build: ./mathserver
    ports:
      - 8081:8080
    environment: 
      ELASTIC_APM_SERVICE_NAME: mathserver            # default to binary name
      ELASTIC_APM_SERVER_URL: http://apm-server:8200
      ELASTIC_APM_METRICS_INTERVAL: 3s                # default to 30sec
      # ELASTIC_APM_LOG_LEVEL: debug
      # ELASTIC_APM_LOG_FILE: stderr
    networks:
      - monitoring
      - app

volumes:
  esdata:
    driver: local

networks: 
  monitoring:
    driver: bridge # default
  app:
